export const styles = {
  container: "relative overflow-hidden w-full p-6 max-w-xl mx-auto mt-10 bg-zinc-900 text-zinc-100 font-sans rounded-2xl border border-zinc-800 shadow-2xl",
  header: "text-xl font-semibold tracking-tight mb-6 text-white",
  fileSection: "flex flex-col gap-3",
  fileBtn: "w-full flex items-center justify-center gap-2 px-4 py-3 border border-dashed border-zinc-700 hover:border-indigo-500 hover:bg-zinc-800/50 rounded-lg transition-colors text-sm font-medium cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed",
  selectedFile: "flex items-center justify-between p-3 bg-zinc-950 border border-zinc-800 rounded-lg",
  filePath: "text-xs text-indigo-400 font-mono truncate mr-2",
  clearBtn: "text-zinc-500 hover:text-red-400 transition-colors cursor-pointer",
  editorSection: "mt-6 pt-6 border-t border-zinc-800 flex flex-col gap-4 animate-in fade-in slide-in-from-top-2",
  inputGroup: "flex flex-col gap-1.5",
  label: "text-xs font-medium text-zinc-400",
  input: "w-full px-3 py-2 bg-zinc-950 border border-zinc-800 rounded-lg outline-none transition-all focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/50 text-sm placeholder:text-zinc-700",
  textarea: "w-full px-3 py-2 bg-zinc-950 border border-zinc-800 rounded-lg outline-none transition-all focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/50 text-sm placeholder:text-zinc-700 resize-none",
  thumbnailSection: "flex flex-col gap-1.5 mt-2",
  thumbnailWrapper: "flex items-center gap-4",
  thumbnailPreview: "w-24 h-24 rounded-lg border border-zinc-800 overflow-hidden bg-zinc-950 flex-shrink-0",
  thumbnailPlaceholder: "w-24 h-24 rounded-lg border border-zinc-800 border-dashed bg-zinc-950 flex items-center justify-center flex-shrink-0",
  secondaryBtn: "px-4 py-2 bg-zinc-800 hover:bg-zinc-700 rounded-lg text-xs font-medium transition-colors cursor-pointer disabled:opacity-50",
  dangerBtn: "px-4 py-2 bg-zinc-950 border border-red-900/30 text-red-400 hover:bg-red-950/30 rounded-lg text-xs font-medium transition-colors cursor-pointer disabled:opacity-50",
  actionSection: "mt-4 pt-4 border-t border-zinc-800 flex justify-end",
  saveBtn: "flex items-center gap-2 px-6 py-2 bg-indigo-600 hover:bg-indigo-500 disabled:bg-zinc-800 disabled:text-zinc-500 text-white text-sm font-bold rounded shadow-lg shadow-indigo-500/10 transition-all active:scale-95 cursor-pointer disabled:cursor-default",
};
